
package javaapplication12;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.ResultSet;



/**
 *
 * @author khaled adawi
 */
public class Statics extends javax.swing.JFrame {

    /**
     * Creates new form Statics
     */
    public Statics() {
        initComponents(); 
        this.setLocationRelativeTo(null);
        ImageIcon appIcon = new ImageIcon(getClass().getResource("/pics/schoollogo64.png")); 
        setIconImage(appIcon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new RoundedPanel(10) ;
        panel1 = new javax.swing.JLabel();
        logoutButton = logoutButton = new RoundButton("Logout");
        backButton = new javax.swing.JButton();
        staticsPanel = new RoundedPanel(20) ;
        jPanel2 = new RoundedPanel(20) ;
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studentsNumber = new javax.swing.JTextField();
        teachersNumber = new javax.swing.JTextField();
        showStudentCount = showStudentCount= new RoundButton("Show");
        showTeacherCount = showTeacherCount= new RoundButton("Show");
        jPanel4 = new RoundedPanel(20) ;
        jLabel3 = new javax.swing.JLabel();
        StudentInfo = new RoundedPanel(20) ;
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        idField = new ModernTextField(20) ;
        nameField = new ModernTextField(20) ;
        dateOfBirthField = new ModernTextField(20) ;
        addressField = new ModernTextField(20) ;
        nationalIdField = new ModernTextField(20) ;
        emailField = new ModernTextField(20) ;
        phoneField = new ModernTextField(20) ;
        gradeField = new ModernTextField(20) ;
        removeStudent = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        studentSearch = new javax.swing.JTextField();
        searchStudentButton = new javax.swing.JButton();
        teacherSearch = new javax.swing.JTextField();
        searchTeacheButton = new javax.swing.JButton();
        jPanel5 = new RoundedPanel(20) ;
        jLabel13 = new javax.swing.JLabel();
        teachrIdField = new ModernTextField(20) ;
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        teacherNameField = new ModernTextField(20) ;
        teacherSubjectField = new ModernTextField(20) ;
        teacherAgeField = new ModernTextField(20) ;
        teacherSalaryField = new ModernTextField(20) ;
        removeTeacher = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ANS Statics");

        jPanel1.setBackground(new java.awt.Color(249, 247, 247));

        jPanel3.setBackground(new java.awt.Color(17, 45, 78));

        panel1.setBackground(new java.awt.Color(17, 45, 78));
        panel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        panel1.setForeground(new java.awt.Color(219, 226, 239));
        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/schoollogo64.png"))); // NOI18N
        panel1.setText("Alex national School");
        panel1.setIconTextGap(15);

        logoutButton.setBackground(new java.awt.Color(247, 148, 29));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(247, 148, 29));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/leftarrow32.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton))
        );

        staticsPanel.setBackground(new java.awt.Color(63, 114, 175));

        jPanel2.setBackground(new java.awt.Color(219, 226, 239));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Number of Students");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Number of Teachers");

        studentsNumber.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        studentsNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        studentsNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentsNumberActionPerformed(evt);
            }
        });

        teachersNumber.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        teachersNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        teachersNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachersNumberActionPerformed(evt);
            }
        });

        showStudentCount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showStudentCount.setText("Show/Refresh");
        showStudentCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStudentCountActionPerformed(evt);
            }
        });

        showTeacherCount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showTeacherCount.setText("Show/Refrsh");
        showTeacherCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTeacherCountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentsNumber)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showStudentCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(teachersNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showTeacherCount, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(studentsNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(teachersNumber))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(showStudentCount)
                                .addGap(40, 40, 40))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showTeacherCount)
                        .addGap(38, 38, 38))))
        );

        jPanel4.setBackground(new java.awt.Color(17, 45, 78));

        jLabel3.setBackground(new java.awt.Color(219, 226, 239));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(219, 226, 239));
        jLabel3.setText("Search Student by ID:");

        StudentInfo.setBackground(new java.awt.Color(63, 114, 175));
        StudentInfo.setForeground(new java.awt.Color(219, 226, 239));

        jLabel4.setBackground(new java.awt.Color(15, 137, 253));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(17, 45, 78));
        jLabel4.setText("Full Name:");

        jLabel5.setBackground(new java.awt.Color(15, 137, 253));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(17, 45, 78));
        jLabel5.setText("Student ID:");

        jLabel6.setBackground(new java.awt.Color(15, 137, 253));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(17, 45, 78));
        jLabel6.setText("Date OF Birth:");

        jLabel7.setBackground(new java.awt.Color(15, 137, 253));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(17, 45, 78));
        jLabel7.setText("Ntional ID:");

        jLabel8.setBackground(new java.awt.Color(15, 137, 253));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(17, 45, 78));
        jLabel8.setText("Address:");

        jLabel9.setBackground(new java.awt.Color(15, 137, 253));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(17, 45, 78));
        jLabel9.setText("Email:");

        jLabel10.setBackground(new java.awt.Color(15, 137, 253));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(17, 45, 78));
        jLabel10.setText("Phone:");

        jLabel11.setBackground(new java.awt.Color(15, 137, 253));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(17, 45, 78));
        jLabel11.setText("Grade:");

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        dateOfBirthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOfBirthFieldActionPerformed(evt);
            }
        });

        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });

        nationalIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalIdFieldActionPerformed(evt);
            }
        });

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });

        gradeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeFieldActionPerformed(evt);
            }
        });

        removeStudent.setBackground(new java.awt.Color(197, 23, 46));
        removeStudent.setForeground(new java.awt.Color(219, 226, 239));
        removeStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/delete.png"))); // NOI18N
        removeStudent.setText("Remove Student");
        removeStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentInfoLayout = new javax.swing.GroupLayout(StudentInfo);
        StudentInfo.setLayout(StudentInfoLayout);
        StudentInfoLayout.setHorizontalGroup(
            StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentInfoLayout.createSequentialGroup()
                        .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentInfoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(dateOfBirthField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentInfoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(StudentInfoLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 5, Short.MAX_VALUE)
                .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentInfoLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel11))
                    .addGroup(StudentInfoLayout.createSequentialGroup()
                        .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(StudentInfoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentInfoLayout.createSequentialGroup()
                                .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nationalIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        StudentInfoLayout.setVerticalGroup(
            StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentInfoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(33, 33, 33)
                .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(nationalIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(dateOfBirthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(removeStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel12.setBackground(new java.awt.Color(219, 226, 239));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(219, 226, 239));
        jLabel12.setText("Search Teacher by ID:");

        studentSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        searchStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/search16.png"))); // NOI18N
        searchStudentButton.setText("Serach");
        searchStudentButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        searchStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStudentButtonActionPerformed(evt);
            }
        });

        teacherSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        searchTeacheButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/search16.png"))); // NOI18N
        searchTeacheButton.setText("Serach");
        searchTeacheButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        searchTeacheButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTeacheButtonActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(63, 114, 175));

        jLabel13.setBackground(new java.awt.Color(219, 226, 239));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(17, 45, 78));
        jLabel13.setText("Teacher ID:");

        teachrIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachrIdFieldActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(219, 226, 239));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(17, 45, 78));
        jLabel14.setText("Name:");

        jLabel15.setBackground(new java.awt.Color(219, 226, 239));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(17, 45, 78));
        jLabel15.setText("Subject:");

        jLabel16.setBackground(new java.awt.Color(219, 226, 239));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(17, 45, 78));
        jLabel16.setText("Age:");

        jLabel17.setBackground(new java.awt.Color(219, 226, 239));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(17, 45, 78));
        jLabel17.setText("Salary:");

        teacherNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherNameFieldActionPerformed(evt);
            }
        });

        teacherSubjectField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherSubjectFieldActionPerformed(evt);
            }
        });

        teacherAgeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherAgeFieldActionPerformed(evt);
            }
        });

        teacherSalaryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherSalaryFieldActionPerformed(evt);
            }
        });

        removeTeacher.setBackground(new java.awt.Color(197, 23, 46));
        removeTeacher.setForeground(new java.awt.Color(219, 226, 239));
        removeTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/delete.png"))); // NOI18N
        removeTeacher.setText("Remove  Teacher");
        removeTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTeacherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teachrIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teacherSalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teacherNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teacherAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(237, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teacherSubjectField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(teachrIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(teacherSalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(teacherNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(teacherAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(teacherSubjectField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StudentInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchStudentButton))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teacherSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchTeacheButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(studentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(teacherSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTeacheButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout staticsPanelLayout = new javax.swing.GroupLayout(staticsPanel);
        staticsPanel.setLayout(staticsPanelLayout);
        staticsPanelLayout.setHorizontalGroup(
            staticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staticsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        staticsPanelLayout.setVerticalGroup(
            staticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staticsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(staticsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staticsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        LogIn login = new LogIn();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed
    
    
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Admin admin = new Admin();
        admin.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void studentsNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsNumberActionPerformed
        studentsNumber.setEditable(false);
        
        
        
    }//GEN-LAST:event_studentsNumberActionPerformed

    private void teachersNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachersNumberActionPerformed
        // TODO add your handling code here:
        teachersNumber.setEditable(false);
    }//GEN-LAST:event_teachersNumberActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
        idField.setEditable(false);

    }//GEN-LAST:event_idFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
        nameField.setEditable(false);
    }//GEN-LAST:event_nameFieldActionPerformed

    private void dateOfBirthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOfBirthFieldActionPerformed
        // TODO add your handling code here:
        dateOfBirthField.setEditable(false);
    }//GEN-LAST:event_dateOfBirthFieldActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
        addressField.setEditable(false);
    }//GEN-LAST:event_addressFieldActionPerformed

    private void nationalIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalIdFieldActionPerformed
        // TODO add your handling code here:
        nationalIdField.setEditable(false);

    }//GEN-LAST:event_nationalIdFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
        emailField.setEditable(false);
    }//GEN-LAST:event_emailFieldActionPerformed

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
        phoneField.setEditable(false);
    }//GEN-LAST:event_phoneFieldActionPerformed

    private void gradeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeFieldActionPerformed
        // TODO add your handling code here:
        gradeField.setEditable(false);
    }//GEN-LAST:event_gradeFieldActionPerformed

    private void teachrIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachrIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachrIdFieldActionPerformed

    private void teacherNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherNameFieldActionPerformed

    private void teacherSubjectFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherSubjectFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherSubjectFieldActionPerformed

    private void teacherAgeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherAgeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherAgeFieldActionPerformed

    private void teacherSalaryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherSalaryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherSalaryFieldActionPerformed

    //Methode to return the total number of Students in the school database
    private void showStudentCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStudentCountActionPerformed
       try (Connection conn = DriverManager.getConnection("jdbc:sqlite:db.db")){
           //SQLite code
            String sql ="SELECT COUNT(*) FROM Student";
            
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            
            if (rs.next()) {
                int count = rs.getInt(1);
                studentsNumber.setText(String.valueOf(count));
            }
            
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_showStudentCountActionPerformed

    //Methode to return the total number of Teacher in the school database
    private void showTeacherCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTeacherCountActionPerformed
        
        try(Connection conn = DriverManager.getConnection("jdbc:sqlite:db.db")) {
            String sql = "SELECT COUNT(*) FROM Teacher";
            
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            
            if (rs.next()) {
                int count = rs.getInt(1);
                teachersNumber.setText(String.valueOf(count));
                
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_showTeacherCountActionPerformed

    
    //button action to get the student data by his id 
    private void searchStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudentButtonActionPerformed
        studentInfo s = new studentInfo();
        
        
        String studentID = studentSearch.getText();
        s.setId(Integer.parseInt(studentSearch.getText()));
        
        if (studentID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter the Student's ID");
        }else{
        
        try(Connection conn = DriverManager.getConnection("jdbc:sqlite:db.db")) {
            
            String sql = "SELECT * FROM Student WHERE ID = ? ";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, studentID);
            
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                idField.setText(rs.getString("ID"));
                nameField.setText(rs.getString("Name"));
                dateOfBirthField.setText(rs.getString("DateOfBirth"));
                emailField.setText(rs.getString("Email"));
                nationalIdField.setText(rs.getString("NationalID"));
                addressField.setText(rs.getString("Address"));
                phoneField.setText(rs.getString("Phone"));
                gradeField.setText(rs.getString("Grade"));
                
            }else{
                JOptionPane.showMessageDialog(null, "No Student Found with this ID ");
                studentSearch.setText("");
            }
            
            
            
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_searchStudentButtonActionPerformed
    //button action to get the Teacher information by his id
    private void searchTeacheButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTeacheButtonActionPerformed
        
        String teacherID = teacherSearch.getText();
        if (teacherID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter the Teacher's ID");
        }else{
        
        try(Connection conn = DriverManager.getConnection("jdbc:sqlite:db.db")) {
            String sql = "SELECT * FROM Teacher WHERE ID = ? ";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, teacherID);
            
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                teachrIdField.setText(rs.getString("ID"));
                teacherNameField.setText(rs.getString("Name"));
                teacherAgeField.setText(rs.getString("Age"));
                teacherSubjectField.setText(rs.getString("Subject"));
                teacherSalaryField.setText(rs.getString("Salary"));
                
            }else{
                JOptionPane.showMessageDialog(null, "No Teacher Found with this ID ");
                teacherSearch.setText("");
            }
            
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_searchTeacheButtonActionPerformed
     
    //Methode to remove a student from the system 
    private void removeStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStudentActionPerformed
        String studentID = studentSearch.getText();
        if (studentID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter the Student's ID");
        }else{
            int confirm = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to delete this student?", "Confirm Delete",
            JOptionPane.YES_NO_OPTION);

             if (confirm != JOptionPane.YES_OPTION) {
             return; 
            }

            
            try(Connection conn = DriverManager.getConnection("jdbc:sqlite:db.db")) {
                String sql = "DELETE FROM Student WHERE ID = ? ";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, studentID);
                
            int rowsAffected = pstmt.executeUpdate();
                if (rowsAffected>0) {
                      JOptionPane.showMessageDialog(null, "Student removed successfully");
            
                    idField.setText("");
                    nameField.setText("");
                    dateOfBirthField.setText("");
                    nationalIdField.setText("");
                    addressField.setText("");
                    emailField.setText("");
                    phoneField.setText("");
                    gradeField.setText("");
                    
                }else{
                JOptionPane.showMessageDialog(null, "Couldn't Remove ");
                }
                
            } catch (Exception e) {
            }
        
        
        
        }
    }//GEN-LAST:event_removeStudentActionPerformed
    
    //Methode to remove a teacher from the system 
    private void removeTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTeacherActionPerformed
        String teacherID = teacherSearch.getText();
        
        if (teacherID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter the Teacher's ID");
        }else{
            int confirm = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to delete this teacher?", "Confirm Delete",
            JOptionPane.YES_NO_OPTION);

             if (confirm != JOptionPane.YES_OPTION) {
             return; 
            }
        
            try(Connection conn = DriverManager.getConnection("jdbc:sqlite:db.db")){
                String sql = "DELETE FROM Teacher WHERE ID = ?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, teacherID);
                
                int rowsAffected = pstmt.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Teacher removed successfully"); 
                
                teachrIdField.setText("");
                teacherNameField.setText("");
                teacherAgeField.setText("");
                teacherSubjectField.setText("");
                teacherSalaryField.setText("");
                
                }else{
                JOptionPane.showMessageDialog(null, "Couldn't Remove ");
                }
   
            } catch (Exception e) {
            }
        
        }
    }//GEN-LAST:event_removeTeacherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statics().setVisible(true);
            }
        });
    }

    //-------------------------------------------END----------------------------
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StudentInfo;
    private javax.swing.JTextField addressField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField dateOfBirthField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField gradeField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nationalIdField;
    private javax.swing.JLabel panel1;
    private javax.swing.JTextField phoneField;
    private javax.swing.JButton removeStudent;
    private javax.swing.JButton removeTeacher;
    private javax.swing.JButton searchStudentButton;
    private javax.swing.JButton searchTeacheButton;
    private javax.swing.JButton showStudentCount;
    private javax.swing.JButton showTeacherCount;
    private javax.swing.JPanel staticsPanel;
    private javax.swing.JTextField studentSearch;
    private javax.swing.JTextField studentsNumber;
    private javax.swing.JTextField teacherAgeField;
    private javax.swing.JTextField teacherNameField;
    private javax.swing.JTextField teacherSalaryField;
    private javax.swing.JTextField teacherSearch;
    private javax.swing.JTextField teacherSubjectField;
    private javax.swing.JTextField teachersNumber;
    private javax.swing.JTextField teachrIdField;
    // End of variables declaration//GEN-END:variables
}
