
package javaapplication12;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author khaled adawi
 */
public class Teacher extends javax.swing.JFrame {

    /**
     * Creates new form Teacher
     */
    public Teacher() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon appIcon = new ImageIcon(getClass().getResource("/pics/schoollogo64.png")); 
        setIconImage(appIcon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new RoundedPanel(10) ;
        panel1 = new javax.swing.JLabel();
        logoutButton = logoutButton = new RoundButton("Logout");
        jPanel1 = new RoundedPanel(20) ;
        jPanel4 = new RoundedPanel(20) ;
        jLabel3 = new javax.swing.JLabel();
        searchStudentId = new javax.swing.JTextField();
        searchStudentButton = new javax.swing.JButton();
        StudentInfo = new RoundedPanel(20) ;
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        idField = new ModernTextField(20) ;
        nameField = new ModernTextField(20) ;
        dateOfBirthField = new ModernTextField(20) ;
        addressField = new ModernTextField(20) ;
        nationalIdField = new ModernTextField(20) ;
        emailField = new ModernTextField(20) ;
        phoneField = new ModernTextField(20) ;
        gradeField = new ModernTextField(20) ;
        showMarksButton = new javax.swing.JButton();
        jPanel7 = new RoundedPanel(20);
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        arabicGradeField = new javax.swing.JTextField();
        englishGradeField = new javax.swing.JTextField();
        mathGradeField = new javax.swing.JTextField();
        scienceGradeField = new javax.swing.JTextField();
        socialstudiesGradeField = new javax.swing.JTextField();
        arabicAdd = new javax.swing.JButton();
        englishAdd = new javax.swing.JButton();
        mathAdd = new javax.swing.JButton();
        scienceAdd = new javax.swing.JButton();
        socialStudiesAdd = new javax.swing.JButton();
        Top10Button = new javax.swing.JButton();
        jPanel8 = new RoundedPanel(20);
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        arabicAbsenceField = new javax.swing.JTextField();
        englishAbsenceField = new javax.swing.JTextField();
        mathAbsenceField = new javax.swing.JTextField();
        scienceAbsenceField = new javax.swing.JTextField();
        socialstudiesAbsenceField = new javax.swing.JTextField();
        arabicAbsenceAdd = new javax.swing.JButton();
        englishAbsenceAdd = new javax.swing.JButton();
        mathAbsenceAdd = new javax.swing.JButton();
        scienceAbsenceAdd = new javax.swing.JButton();
        socialStudiesAbsenceAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ANS Teachers Portal");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(249, 247, 247));

        jPanel3.setBackground(new java.awt.Color(17, 45, 78));

        panel1.setBackground(new java.awt.Color(17, 45, 78));
        panel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        panel1.setForeground(new java.awt.Color(219, 226, 239));
        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/schoollogo64.png"))); // NOI18N
        panel1.setText("Alex national School");
        panel1.setIconTextGap(15);

        logoutButton.setBackground(new java.awt.Color(247, 148, 29));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(17, 45, 78));

        jPanel4.setBackground(new java.awt.Color(63, 114, 175));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(219, 226, 239));
        jLabel3.setText("Search Student by ID:");

        searchStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/search16.png"))); // NOI18N
        searchStudentButton.setText("Serach");
        searchStudentButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        searchStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStudentButtonActionPerformed(evt);
            }
        });

        StudentInfo.setBackground(new java.awt.Color(17, 45, 78));
        StudentInfo.setForeground(new java.awt.Color(219, 226, 239));

        jLabel2.setBackground(new java.awt.Color(15, 137, 253));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(219, 226, 239));
        jLabel2.setText("Full Name:");

        jLabel4.setBackground(new java.awt.Color(15, 137, 253));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(219, 226, 239));
        jLabel4.setText("Student ID:");

        jLabel5.setBackground(new java.awt.Color(15, 137, 253));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(219, 226, 239));
        jLabel5.setText("Date OF Birth:");

        jLabel6.setBackground(new java.awt.Color(15, 137, 253));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(219, 226, 239));
        jLabel6.setText("Ntional ID:");

        jLabel7.setBackground(new java.awt.Color(15, 137, 253));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(219, 226, 239));
        jLabel7.setText("Address:");

        jLabel9.setBackground(new java.awt.Color(15, 137, 253));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(219, 226, 239));
        jLabel9.setText("Email:");

        jLabel10.setBackground(new java.awt.Color(15, 137, 253));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(219, 226, 239));
        jLabel10.setText("Phone:");

        jLabel11.setBackground(new java.awt.Color(15, 137, 253));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(219, 226, 239));
        jLabel11.setText("Grade:");

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        dateOfBirthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOfBirthFieldActionPerformed(evt);
            }
        });

        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });

        nationalIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalIdFieldActionPerformed(evt);
            }
        });

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });

        gradeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeFieldActionPerformed(evt);
            }
        });

        showMarksButton.setBackground(new java.awt.Color(0, 255, 0));
        showMarksButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showMarksButton.setForeground(new java.awt.Color(0, 0, 0));
        showMarksButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/marks16.png"))); // NOI18N
        showMarksButton.setText("Grades&Absence");
        showMarksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMarksButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentInfoLayout = new javax.swing.GroupLayout(StudentInfo);
        StudentInfo.setLayout(StudentInfoLayout);
        StudentInfoLayout.setHorizontalGroup(
            StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentInfoLayout.createSequentialGroup()
                        .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentInfoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(dateOfBirthField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentInfoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(StudentInfoLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentInfoLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel11))
                    .addGroup(StudentInfoLayout.createSequentialGroup()
                        .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(StudentInfoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentInfoLayout.createSequentialGroup()
                                .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nationalIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phoneField)
                    .addComponent(gradeField)
                    .addComponent(showMarksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        StudentInfoLayout.setVerticalGroup(
            StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentInfoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(33, 33, 33)
                .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(nationalIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dateOfBirthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showMarksButton))
                .addGap(13, 13, 13))
        );

        jPanel7.setBackground(new java.awt.Color(17, 45, 78));

        jLabel8.setBackground(new java.awt.Color(15, 137, 253));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(219, 226, 239));
        jLabel8.setText("Subjects");

        jLabel12.setBackground(new java.awt.Color(15, 137, 253));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(219, 226, 239));
        jLabel12.setText("Arabic");

        jLabel13.setBackground(new java.awt.Color(15, 137, 253));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(219, 226, 239));
        jLabel13.setText("English");

        jLabel14.setBackground(new java.awt.Color(15, 137, 253));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(219, 226, 239));
        jLabel14.setText("Mathmatics");

        jLabel15.setBackground(new java.awt.Color(15, 137, 253));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(219, 226, 239));
        jLabel15.setText("Science");

        jLabel16.setBackground(new java.awt.Color(15, 137, 253));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(219, 226, 239));
        jLabel16.setText("Social Studies");

        jLabel1.setBackground(new java.awt.Color(219, 226, 239));
        jLabel1.setForeground(new java.awt.Color(219, 226, 239));
        jLabel1.setText("Add grade");

        jLabel17.setBackground(new java.awt.Color(219, 226, 239));
        jLabel17.setForeground(new java.awt.Color(219, 226, 239));
        jLabel17.setText("Add grade");

        jLabel18.setBackground(new java.awt.Color(219, 226, 239));
        jLabel18.setForeground(new java.awt.Color(219, 226, 239));
        jLabel18.setText("Add grade");

        jLabel19.setBackground(new java.awt.Color(219, 226, 239));
        jLabel19.setForeground(new java.awt.Color(219, 226, 239));
        jLabel19.setText("Add grade");

        jLabel20.setBackground(new java.awt.Color(219, 226, 239));
        jLabel20.setForeground(new java.awt.Color(219, 226, 239));
        jLabel20.setText("Add grade");

        arabicGradeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arabicGradeFieldActionPerformed(evt);
            }
        });

        englishGradeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishGradeFieldActionPerformed(evt);
            }
        });

        mathGradeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathGradeFieldActionPerformed(evt);
            }
        });

        scienceGradeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scienceGradeFieldActionPerformed(evt);
            }
        });

        socialstudiesGradeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialstudiesGradeFieldActionPerformed(evt);
            }
        });

        arabicAdd.setBackground(new java.awt.Color(17, 45, 78));
        arabicAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        arabicAdd.setForeground(new java.awt.Color(219, 226, 239));
        arabicAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/add24.png"))); // NOI18N
        arabicAdd.setText("Add");
        arabicAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arabicAddActionPerformed(evt);
            }
        });

        englishAdd.setBackground(new java.awt.Color(17, 45, 78));
        englishAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        englishAdd.setForeground(new java.awt.Color(219, 226, 239));
        englishAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/add24.png"))); // NOI18N
        englishAdd.setText("Add");
        englishAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishAddActionPerformed(evt);
            }
        });

        mathAdd.setBackground(new java.awt.Color(17, 45, 78));
        mathAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mathAdd.setForeground(new java.awt.Color(219, 226, 239));
        mathAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/add24.png"))); // NOI18N
        mathAdd.setText("Add");
        mathAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathAddActionPerformed(evt);
            }
        });

        scienceAdd.setBackground(new java.awt.Color(17, 45, 78));
        scienceAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        scienceAdd.setForeground(new java.awt.Color(219, 226, 239));
        scienceAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/add24.png"))); // NOI18N
        scienceAdd.setText("Add");
        scienceAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scienceAddActionPerformed(evt);
            }
        });

        socialStudiesAdd.setBackground(new java.awt.Color(17, 45, 78));
        socialStudiesAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        socialStudiesAdd.setForeground(new java.awt.Color(219, 226, 239));
        socialStudiesAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/add24.png"))); // NOI18N
        socialStudiesAdd.setText("Add");
        socialStudiesAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialStudiesAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(arabicGradeField)
                    .addComponent(arabicAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(englishGradeField, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(englishAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel14)
                    .addComponent(mathGradeField, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(mathAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(scienceGradeField, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(scienceAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(socialstudiesGradeField)
                    .addComponent(socialStudiesAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arabicGradeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(englishGradeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mathGradeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scienceGradeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(socialstudiesGradeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arabicAdd)
                    .addComponent(englishAdd)
                    .addComponent(mathAdd)
                    .addComponent(scienceAdd)
                    .addComponent(socialStudiesAdd))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Top10Button.setBackground(new java.awt.Color(247, 148, 29));
        Top10Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Top10Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/top32.png"))); // NOI18N
        Top10Button.setText("Top 10");
        Top10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Top10ButtonActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(17, 45, 78));

        jLabel21.setBackground(new java.awt.Color(15, 137, 253));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(219, 226, 239));
        jLabel21.setText("Absence");

        jLabel22.setBackground(new java.awt.Color(15, 137, 253));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(219, 226, 239));
        jLabel22.setText("Arabic");

        jLabel23.setBackground(new java.awt.Color(15, 137, 253));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(219, 226, 239));
        jLabel23.setText("English");

        jLabel24.setBackground(new java.awt.Color(15, 137, 253));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(219, 226, 239));
        jLabel24.setText("Mathmatics");

        jLabel25.setBackground(new java.awt.Color(15, 137, 253));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(219, 226, 239));
        jLabel25.setText("Science");

        jLabel26.setBackground(new java.awt.Color(15, 137, 253));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(219, 226, 239));
        jLabel26.setText("Social Studies");

        jLabel27.setBackground(new java.awt.Color(219, 226, 239));
        jLabel27.setForeground(new java.awt.Color(219, 226, 239));
        jLabel27.setText("Add 1 if absent");

        jLabel28.setBackground(new java.awt.Color(219, 226, 239));
        jLabel28.setForeground(new java.awt.Color(219, 226, 239));
        jLabel28.setText("Add 1 if absent");

        jLabel29.setBackground(new java.awt.Color(219, 226, 239));
        jLabel29.setForeground(new java.awt.Color(219, 226, 239));
        jLabel29.setText("Add 1 if absent");

        jLabel30.setBackground(new java.awt.Color(219, 226, 239));
        jLabel30.setForeground(new java.awt.Color(219, 226, 239));
        jLabel30.setText("Add 1 if absent");

        jLabel31.setBackground(new java.awt.Color(219, 226, 239));
        jLabel31.setForeground(new java.awt.Color(219, 226, 239));
        jLabel31.setText("Add 1 if absent");

        arabicAbsenceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arabicAbsenceFieldActionPerformed(evt);
            }
        });

        englishAbsenceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishAbsenceFieldActionPerformed(evt);
            }
        });

        mathAbsenceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathAbsenceFieldActionPerformed(evt);
            }
        });

        scienceAbsenceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scienceAbsenceFieldActionPerformed(evt);
            }
        });

        socialstudiesAbsenceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialstudiesAbsenceFieldActionPerformed(evt);
            }
        });

        arabicAbsenceAdd.setBackground(new java.awt.Color(17, 45, 78));
        arabicAbsenceAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        arabicAbsenceAdd.setForeground(new java.awt.Color(219, 226, 239));
        arabicAbsenceAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/add24.png"))); // NOI18N
        arabicAbsenceAdd.setText("Add");
        arabicAbsenceAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arabicAbsenceAddActionPerformed(evt);
            }
        });

        englishAbsenceAdd.setBackground(new java.awt.Color(17, 45, 78));
        englishAbsenceAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        englishAbsenceAdd.setForeground(new java.awt.Color(219, 226, 239));
        englishAbsenceAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/add24.png"))); // NOI18N
        englishAbsenceAdd.setText("Add");
        englishAbsenceAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishAbsenceAddActionPerformed(evt);
            }
        });

        mathAbsenceAdd.setBackground(new java.awt.Color(17, 45, 78));
        mathAbsenceAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mathAbsenceAdd.setForeground(new java.awt.Color(219, 226, 239));
        mathAbsenceAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/add24.png"))); // NOI18N
        mathAbsenceAdd.setText("Add");
        mathAbsenceAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathAbsenceAddActionPerformed(evt);
            }
        });

        scienceAbsenceAdd.setBackground(new java.awt.Color(17, 45, 78));
        scienceAbsenceAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        scienceAbsenceAdd.setForeground(new java.awt.Color(219, 226, 239));
        scienceAbsenceAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/add24.png"))); // NOI18N
        scienceAbsenceAdd.setText("Add");
        scienceAbsenceAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scienceAbsenceAddActionPerformed(evt);
            }
        });

        socialStudiesAbsenceAdd.setBackground(new java.awt.Color(17, 45, 78));
        socialStudiesAbsenceAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        socialStudiesAbsenceAdd.setForeground(new java.awt.Color(219, 226, 239));
        socialStudiesAbsenceAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/add24.png"))); // NOI18N
        socialStudiesAbsenceAdd.setText("Add");
        socialStudiesAbsenceAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialStudiesAbsenceAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(arabicAbsenceField)
                    .addComponent(arabicAbsenceAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(englishAbsenceField)
                    .addComponent(englishAbsenceAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addGap(85, 85, 85)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel24)
                    .addComponent(mathAbsenceField)
                    .addComponent(mathAbsenceAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(scienceAbsenceField)
                    .addComponent(scienceAbsenceAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel31)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(socialstudiesAbsenceField)
                    .addComponent(socialStudiesAbsenceAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arabicAbsenceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(englishAbsenceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mathAbsenceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scienceAbsenceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(socialstudiesAbsenceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arabicAbsenceAdd)
                    .addComponent(englishAbsenceAdd)
                    .addComponent(mathAbsenceAdd)
                    .addComponent(scienceAbsenceAdd)
                    .addComponent(socialStudiesAbsenceAdd))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchStudentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Top10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(StudentInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Top10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        LogIn login = new LogIn();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
        idField.setEditable(false);

    }//GEN-LAST:event_idFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
        nameField.setEditable(false);
    }//GEN-LAST:event_nameFieldActionPerformed

    private void dateOfBirthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOfBirthFieldActionPerformed
        // TODO add your handling code here:
        dateOfBirthField.setEditable(false);
    }//GEN-LAST:event_dateOfBirthFieldActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
        addressField.setEditable(false);
    }//GEN-LAST:event_addressFieldActionPerformed

    private void nationalIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalIdFieldActionPerformed
        // TODO add your handling code here:
        nationalIdField.setEditable(false);

    }//GEN-LAST:event_nationalIdFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
        emailField.setEditable(false);
    }//GEN-LAST:event_emailFieldActionPerformed

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
        phoneField.setEditable(false);
    }//GEN-LAST:event_phoneFieldActionPerformed

    private void gradeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeFieldActionPerformed
        // TODO add your handling code here:
        gradeField.setEditable(false);
    }//GEN-LAST:event_gradeFieldActionPerformed

    private void arabicGradeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arabicGradeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arabicGradeFieldActionPerformed

    private void englishGradeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishGradeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_englishGradeFieldActionPerformed

    private void mathGradeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathGradeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mathGradeFieldActionPerformed

    private void scienceGradeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scienceGradeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scienceGradeFieldActionPerformed

    private void socialstudiesGradeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialstudiesGradeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_socialstudiesGradeFieldActionPerformed
     
    private void Top10ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Top10ButtonActionPerformed
        // TODO add your handling code here:
         Dashboard dashboard = new Dashboard();
         dashboard.setVisible(true);
         dispose();
         
    }//GEN-LAST:event_Top10ButtonActionPerformed

    //methode to get students information by his id
    private void searchStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudentButtonActionPerformed
        String studentID = searchStudentId.getText();
        
        if (studentID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter the Student's ID");
        }else{
        
        try(Connection conn = DriverManager.getConnection("jdbc:sqlite:db.db")) {
            String sql = "SELECT * FROM Student WHERE ID = ? ";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, studentID);
            
            
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                idField.setText(rs.getString("ID"));
                nameField.setText(rs.getString("Name"));
                dateOfBirthField.setText(rs.getString("DateOfBirth"));
                emailField.setText(rs.getString("Email"));
                nationalIdField.setText(rs.getString("NationalID"));
                addressField.setText(rs.getString("Address"));
                phoneField.setText(rs.getString("Phone"));
                gradeField.setText(rs.getString("Grade"));
                
            }else{
                JOptionPane.showMessageDialog(null, "No Student Found with this ID ");
                searchStudentId.setText("");
            }
            
            
            
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_searchStudentButtonActionPerformed
    private void showMarksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMarksButtonActionPerformed
       //Method to view the student Marks and Absence 
        String studentID = searchStudentId.getText();
       
        if (studentID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter the Student's ID");
        }else{
            ShowGrades gradesWindow = new ShowGrades(studentID);
            gradesWindow.setVisible(true);
            
        
        }
        
        
    }//GEN-LAST:event_showMarksButtonActionPerformed
     //Adding marks to Arabic
    private void arabicAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arabicAddActionPerformed
        String markText = arabicGradeField.getText();
        String studentID = searchStudentId.getText();
        
        if (studentID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter the Student's ID");
        }else{
        if (markText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a mark");
            
        }else{
            try(Connection conn = DriverManager.getConnection("jdbc:sqlite:db.db")) {
                int mark = Integer.parseInt(markText);
                
                String sql = "UPDATE Student SET Arabic = Arabic + ? WHERE ID = ? ";
                
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1, mark);
                pstmt.setString(2,studentID);
                
                 int rowsUpdated = pstmt.executeUpdate();
                    if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(null, "Mark added successfully!");
                    arabicGradeField.setText("");
                    
                }   else {
                    JOptionPane.showMessageDialog(null, "Student not found!");
                    
                }
                
                
            } catch (Exception e) {
            }
        
        
        
        }}
    }//GEN-LAST:event_arabicAddActionPerformed
    
    //Adding marks to english
    private void englishAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishAddActionPerformed
        String markText = englishGradeField.getText();
        String studentID = searchStudentId.getText();
        
        if (studentID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter the Student's ID");
        }else{
        if (markText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a mark");
            
        }else{
            try(Connection conn = DriverManager.getConnection("jdbc:sqlite:db.db")) {
                int mark = Integer.parseInt(markText);
                
                String sql = "UPDATE Student SET English = English + ? WHERE ID = ? ";   
                
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1, mark);
                pstmt.setString(2,studentID);
                
                 int rowsUpdated = pstmt.executeUpdate();
                    if (rowsUpdated > 0) {
                        JOptionPane.showMessageDialog(null, "Mark added successfully!");
                        englishGradeField.setText("");
                }   else {
                         JOptionPane.showMessageDialog(null, "Student not found!");
                    
                }
                
                
            } catch (Exception e) {
            }
        
        
        
        }}
    }//GEN-LAST:event_englishAddActionPerformed

    
    //Adding marks to math
    private void mathAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathAddActionPerformed
        String markText = mathGradeField.getText();
        String studentID = searchStudentId.getText();
        
        if (studentID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter the Student's ID");
        }else{
        if (markText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a mark");
            
        }else{
            try(Connection conn = DriverManager.getConnection("jdbc:sqlite:db.db")) {
                int mark = Integer.parseInt(markText);
                
                String sql = "UPDATE Student SET Mathmatics = Mathmatics + ? WHERE ID = ? ";   
                
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1, mark);
                pstmt.setString(2,studentID);
                
                 int rowsUpdated = pstmt.executeUpdate();
                    if (rowsUpdated > 0) {
                        JOptionPane.showMessageDialog(null, "Mark added successfully!");
                        mathGradeField.setText("");
                }   else {
                         JOptionPane.showMessageDialog(null, "Student not found!");
                    
                }
                
                
            } catch (Exception e) {
            }
        }}
        
        
    }//GEN-LAST:event_mathAddActionPerformed

    //Adding marks to science
    private void scienceAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scienceAddActionPerformed
       String markText = scienceGradeField.getText();
        String studentID = searchStudentId.getText();
        
        if (studentID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter the Student's ID");
        }else{
        if (markText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a mark");
            
        }else{
            try(Connection conn = DriverManager.getConnection("jdbc:sqlite:db.db")) {
                int mark = Integer.parseInt(markText);
                
                String sql = "UPDATE Student SET Science = Science + ? WHERE ID = ? ";   
                
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1, mark);
                pstmt.setString(2,studentID);
                
                 int rowsUpdated = pstmt.executeUpdate();
                    if (rowsUpdated > 0) {
                        JOptionPane.showMessageDialog(null, "Mark added successfully!");
                        scienceGradeField.setText("");
                }   else {
                         JOptionPane.showMessageDialog(null, "Student not found!");
                    
                }
                
                
            } catch (Exception e) {
            }
        
        
        
        }}
    }//GEN-LAST:event_scienceAddActionPerformed
 
    
    //Adding marks to social studies
    private void socialStudiesAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialStudiesAddActionPerformed
        String markText = socialstudiesGradeField.getText();
        String studentID = searchStudentId.getText();
        
        if (studentID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter the Student's ID");
        }else{
        if (markText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a mark");
            
        }else{
            try(Connection conn = DriverManager.getConnection("jdbc:sqlite:db.db")) {
                int mark = Integer.parseInt(markText);
                
                String sql = "UPDATE Student SET SocialStudies = SocialStudies + ? WHERE ID = ? ";   
                
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1, mark);
                pstmt.setString(2,studentID);
                
                 int rowsUpdated = pstmt.executeUpdate();
                    if (rowsUpdated > 0) {
                        JOptionPane.showMessageDialog(null, "Mark added successfully!");
                        socialstudiesGradeField.setText("");
                }   else {
                         JOptionPane.showMessageDialog(null, "Student not found!");
                    
                }
                
                
            } catch (Exception e) {
            }
        
        
        
        }}
    }//GEN-LAST:event_socialStudiesAddActionPerformed

    private void arabicAbsenceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arabicAbsenceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arabicAbsenceFieldActionPerformed

    private void englishAbsenceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishAbsenceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_englishAbsenceFieldActionPerformed

    private void mathAbsenceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathAbsenceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mathAbsenceFieldActionPerformed

    private void scienceAbsenceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scienceAbsenceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scienceAbsenceFieldActionPerformed

    private void socialstudiesAbsenceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialstudiesAbsenceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_socialstudiesAbsenceFieldActionPerformed
  
    
    //Adding absence to arabic
    private void arabicAbsenceAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arabicAbsenceAddActionPerformed
    String absenceText = arabicAbsenceField.getText();
    String studentID = searchStudentId.getText(); 
    
    if (absenceText.isEmpty() || studentID.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter both absence number and Student ID.");
        
    }

    try (Connection conn = DriverManager.getConnection("jdbc:sqlite:db.db")) {
        int newAbsence = Integer.parseInt(absenceText);

        String sql = "UPDATE Student SET ArabicAbsence = COALESCE(ArabicAbsence, 0) + ? WHERE ID = ?";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setInt(1, newAbsence);
        pstmt.setString(2, studentID);

        int rows = pstmt.executeUpdate();

        if (rows > 0) {
            JOptionPane.showMessageDialog(null, "absence Added successfully.");
            arabicAbsenceField.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Student ID not found.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_arabicAbsenceAddActionPerformed

    
    //Adding absence to  english
    private void englishAbsenceAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishAbsenceAddActionPerformed
        String absenceText = englishAbsenceField.getText();
        String studentID = searchStudentId.getText(); 

    if (absenceText.isEmpty() || studentID.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter both absence number and Student ID.");
        return;
    }

    try (Connection conn = DriverManager.getConnection("jdbc:sqlite:db.db")) {
        int newAbsence = Integer.parseInt(absenceText);

        String sql = "UPDATE Student SET EnglishAbsence = COALESCE(EnglishAbsence, 0) + ? WHERE ID = ?";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setInt(1, newAbsence);
        pstmt.setString(2, studentID);

        int rows = pstmt.executeUpdate();

        if (rows > 0) {
            JOptionPane.showMessageDialog(null, "absence Added successfully.");
            englishAbsenceField.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Student ID not found.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_englishAbsenceAddActionPerformed

    
    //Adding absence to  math
    private void mathAbsenceAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathAbsenceAddActionPerformed
        String absenceText = mathAbsenceField.getText();
        String studentID = searchStudentId.getText(); 

    if (absenceText.isEmpty() || studentID.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter both absence number and Student ID.");
        return;
    }

    try (Connection conn = DriverManager.getConnection("jdbc:sqlite:db.db")) {
        int newAbsence = Integer.parseInt(absenceText);

        String sql = "UPDATE Student SET MathmaticsAbsence = COALESCE(MathmaticsAbsence, 0) + ? WHERE ID = ?";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setInt(1, newAbsence);
        pstmt.setString(2, studentID);

        int rows = pstmt.executeUpdate();

        if (rows > 0) {
            JOptionPane.showMessageDialog(null, "absence Added successfully.");
            mathAbsenceField.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Student ID not found.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_mathAbsenceAddActionPerformed

    //Adding absence to  scinece
    private void scienceAbsenceAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scienceAbsenceAddActionPerformed
        String absenceText = scienceAbsenceField.getText();
        String studentID   = searchStudentId.getText(); 

    if (absenceText.isEmpty() || studentID.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter both absence number and Student ID.");
        return;
    }

    try (Connection conn = DriverManager.getConnection("jdbc:sqlite:db.db")) {
        int newAbsence = Integer.parseInt(absenceText);

        String sql = "UPDATE Student SET ScienceAbsence = COALESCE(ScienceAbsence, 0) + ? WHERE ID = ?";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setInt(1, newAbsence);
        pstmt.setString(2, studentID);

        int rows = pstmt.executeUpdate();

        if (rows > 0) {
            JOptionPane.showMessageDialog(null, "absence Added successfully.");
            scienceAbsenceField.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Student ID not found.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_scienceAbsenceAddActionPerformed

    //Adding absence to social studies
    private void socialStudiesAbsenceAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialStudiesAbsenceAddActionPerformed
        String absenceText = socialstudiesAbsenceField.getText();
        String studentID   = searchStudentId.getText(); 

    if (absenceText.isEmpty() || studentID.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter both absence number and Student ID.");
        return;
    }

    try (Connection conn = DriverManager.getConnection("jdbc:sqlite:db.db")) {
        int newAbsence = Integer.parseInt(absenceText);

        String sql = "UPDATE Student SET SocialStudiesAbsence = COALESCE(SocialStudiesAbsence, 0) + ? WHERE ID = ?";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setInt(1, newAbsence);
        pstmt.setString(2, studentID);

        int rows = pstmt.executeUpdate();

        if (rows > 0) {
            JOptionPane.showMessageDialog(null, "absence Added successfully.");
            socialstudiesAbsenceField.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Student ID not found.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_socialStudiesAbsenceAddActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StudentInfo;
    private javax.swing.JButton Top10Button;
    private javax.swing.JTextField addressField;
    private javax.swing.JButton arabicAbsenceAdd;
    private javax.swing.JTextField arabicAbsenceField;
    private javax.swing.JButton arabicAdd;
    private javax.swing.JTextField arabicGradeField;
    private javax.swing.JTextField dateOfBirthField;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton englishAbsenceAdd;
    private javax.swing.JTextField englishAbsenceField;
    private javax.swing.JButton englishAdd;
    private javax.swing.JTextField englishGradeField;
    private javax.swing.JTextField gradeField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton mathAbsenceAdd;
    private javax.swing.JTextField mathAbsenceField;
    private javax.swing.JButton mathAdd;
    private javax.swing.JTextField mathGradeField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nationalIdField;
    private javax.swing.JLabel panel1;
    private javax.swing.JTextField phoneField;
    private javax.swing.JButton scienceAbsenceAdd;
    private javax.swing.JTextField scienceAbsenceField;
    private javax.swing.JButton scienceAdd;
    private javax.swing.JTextField scienceGradeField;
    private javax.swing.JButton searchStudentButton;
    private javax.swing.JTextField searchStudentId;
    private javax.swing.JButton showMarksButton;
    private javax.swing.JButton socialStudiesAbsenceAdd;
    private javax.swing.JButton socialStudiesAdd;
    private javax.swing.JTextField socialstudiesAbsenceField;
    private javax.swing.JTextField socialstudiesGradeField;
    // End of variables declaration//GEN-END:variables
}
